# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('adress_1', models.CharField(max_length=20)),
                ('adress_2', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=20)),
                ('date_refusal', models.DateTimeField(blank=True, null=True)),
                ('date_acceptance', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField()),
                ('ref', models.CharField(max_length=20)),
                ('date_payment', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('siret', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('adress_1', models.CharField(max_length=20)),
                ('adress_2', models.CharField(max_length=20, verbose_name='adress_2')),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Profile'),
        ),
        migrations.AddField(
            model_name='devis',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Profile'),
        ),
        migrations.AddField(
            model_name='contain',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Devis'),
        ),
        migrations.AddField(
            model_name='contain',
            name='facture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Facture'),
        ),
    ]
