# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturier', '0002_auto_20170620_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name_plural': 'Devis'},
        ),
    ]
