# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturier', '0005_devis_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_refusal', models.DateTimeField(blank=True, null=True)),
                ('date_acceptance', models.DateTimeField(blank=True, null=True)),
                ('date_payment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='lignedevis',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='facture',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='entreprise',
            new_name='enterprise',
        ),
        migrations.DeleteModel(
            name='Devis',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='LigneDevis',
        ),
        migrations.DeleteModel(
            name='LigneFacture',
        ),
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Client'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Profile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Status'),
        ),
    ]
