# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturier', '0006_auto_20170623_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='entreprise',
            new_name='enterprise',
        ),
    ]
