# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturier', '0008_auto_20170623_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='quantity',
        ),
        migrations.AddField(
            model_name='line',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_facturier.Proposal'),
        ),
    ]
