# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturier', '0010_auto_20170703_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DEVEC', 'Devis en cours'), ('FACEC', 'Facture en cours'), ('DPERD', 'Perdu'), ('FPAYE', 'Pay\xe9')], max_length=150),
        ),
    ]
