# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturier', '0011_auto_20170703_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mail_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
